feeble attempt at assemblyscript
jordan-rash/examples pull request #1
Opened 2021-04-26 00:53 UTC by matthewtgilbride

This doesn't work - but the `HandleRequest` theoretically copies the logic from the rust implementation.

2021-04-26 15:33 UTC, brooksmtownsend requested changes
Hey @matthewtgilbride ! Thanks for doing the first pass at the implementation here, I changed a few things to remove the json encoder piece (it's pretty annoying) but the snippets that I posted are functional 😄

2021-04-26 15:33 UTC, brooksmtownsend commented on calculator/assemblyscript/index.ts
> +}
Howdy! I trimmed this up and verified it worked (apparently AS doesn't support string interpolation :/)
```
function HandleRequest(request: Request): Response {

  const nums = request.queryString.split(",")
  const numOne = parseInt(nums[0])
  const numTwo = parseInt(nums[1])
  let result = ""

  if (request.path == "/add") {
    result = "add: " + numOne.toString() + " + " + numTwo.toString() + " = " + (numOne + numTwo).toString()
  } else if (request.path == "/sub") {
    result = "subtract: " + numOne.toString() + " - " + numTwo.toString() + " = " + (numOne - numTwo).toString()
  } else if (request.path == "/div") {
    if (numTwo === 0) {
      result = "Can not divide by zero!"
    } else {
      result = "divide: " + numOne.toString() + " / " + numTwo.toString() + " = " + (numOne / numTwo).toString()
    }
  } else {
    result = "Unsupported operation"
  }

  return new ResponseBuilder()
    .withStatusCode(200)
    .withStatus("OK")
    .withBody(String.UTF8.encode(result, true))
    .build();
}
```

2021-04-26 15:33 UTC, brooksmtownsend commented on calculator/assemblyscript/index.ts
> +import { JSONEncoder } from "assemblyscript-json";
Using the below snippet, you no longer need this dependency

2021-04-26 15:33 UTC, brooksmtownsend commented on calculator/assemblyscript/index.ts
> +import { HealthCheckResponse, HealthCheckRequest, Handlers as CoreHandlers, HealthCheckResponseBuilder } from "@wasmcloud/actor-core/assembly/index";
For these, the `/assembly/index` suffix can be removed

2021-04-26 15:33 UTC, brooksmtownsend commented on calculator/assemblyscript/package.json
> +    "assemblyscript-json": "git+https://github.com/nearprotocol/assemblyscript-json"
You can remove `assemblyscript-json` and update the wasmcloud deps to:
```
    "@wasmcloud/actor-core": "^0.1.2",
    "@wasmcloud/actor-http-server": "^0.1.4"
```

2021-04-27 19:54 UTC, jordan-rash commented
@matthewtgilbride Do you mind accepting Brooks changes and finishing up this PR?  Ill merge it once you say its working on your end 😸

2021-05-03 11:37 UTC, matthewtgilbride commented
@jordan-rash accepted @brooksmtownsend 's changes, followed the assemblyscript quick start, and this now compiles/builds on my machine.  Let me know if it works for you 👍 

Sorry for the delay - just submitted the request to push to public github from my work machine - which should help to reduce my flakiness 😉

2021-05-03 12:58 UTC, brooksmtownsend requested changes

2021-05-03 12:58 UTC, brooksmtownsend commented on calculator/assemblyscript/assembly/index.ts
>    }
Mostly looks good, we're just going to want to verify that the String `===` is the same logically as `==`. It may do a direct object comparison which would always result in the `Unsupported operation` piece, once I'm on my machine I'll test.

2021-05-03 16:29 UTC, brooksmtownsend commented on calculator/assemblyscript/assembly/index.ts
>    }
@jordan-rash yeah I confirmed that this does _not_ work, simply because of the triple equals. The comparisons of `request.path` should be changed to double equals `==`, but the `numTwo === 0` can stay. I can't make this change, but if you go ahead and do it I'll approve

2021-05-03 16:33 UTC, merged